services:
  server:
    ports:
      - "8080:8080"
    image: censys-kv-server:0.1.0
  client:
    ports:
      - "8081:8081"
    image: censys-kv-client:0.1.0

networks:
  default:
    external:
      name: censys-kv-network
